mybatis:
  type-aliases-package: macro.blu.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: 'true'
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  address: 0.0.0.0
  port: '13000'
spring:
  profiles:
    active: prod
  datasource:
    password: test123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: poly
    url: jdbc:mysql://localhost:20312/myDB
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
  server:
    address: localhost
    port: 13001